version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 99
  assignees:
  - samhamilton
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 99
  assignees:
  - samhamilton
- package-ecosystem: npm
  directory: "/assets"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 99
  assignees:
  - samhamilton
